import { ReactQuery } from '@/components/ReactQuery'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavigationBar from '@/components/landing-page/NavigationBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={``} >
      <NavigationBar />
        <ReactQuery>
          {children}
        </ReactQuery>
      </body>
    </html>
  )
}
