import { ReactQuery } from "@/components/ReactQuery";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextAuthProvider from "@/components/NextAuthProvider";
import { Session } from "next-auth";
import { ReactNode } from "react";
import Loading from "@/components/loading";

const inter = Inter({ subsets: ["latin"] });

interface NextAuthProps {
  children: ReactNode;
  session: Session | null | undefined;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }: NextAuthProps) {
  return (
    <html lang="en">
      <body className={``}>
        <NextAuthProvider session={session}>
          <ReactQuery>
            <Loading>{children}</Loading>
          </ReactQuery>
        </NextAuthProvider>
      </body>
    </html>
  );
}
